# Generated by Django 3.0.4 on 2020-03-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_auto_20200306_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='file_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='image_list',
            field=models.TextField(null=True),
        ),
    ]
