# Generated by Django 3.0.4 on 2020-03-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0004_auto_20200309_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
