# Generated by Django 3.0.4 on 2020-03-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0006_memo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='image_list',
        ),
    ]
