export const GET_MEMOS = "GET_MEMOS"
export const ADD_MEMO = "ADD_MEMO"
export const UPDATE_MEMO = "UPDATE_MEMO"
export const DELETE_MEMO = "DELETE_MEMO"
export const SELECT_MEMO = "SELECT_MEMO"
export const SEARCH_CHANGED = "SEARCH_CHANGED"
export const GET_ERRORS = "GET_ERRORS"
export const CREATE_MESSAGE = "CREATE_MESSAGE"